(let z (lambda f (lambda x x)))
(let s (lambda n (lambda f (lambda x (f ((n f) x))))))
(let one (s z))
(let two (s one))
(let ten (s (s (s (s (s (s (s (s (s (s z)))))))))))
(let exp (lambda m (lambda n (n m))))
(let display (lambda n ((n (lambda x (+ x 1))) 0)))

(print 'meoww)
(print 'mrrrrp)
(+ 21 23)
